name: Build and Release

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install -y ninja-build libx11-dev libxrandr-dev libxi-dev libxext-dev libgl1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev


    - name: Install Ninja (Windows)
      if: runner.os == 'Windows'
      run: choco install ninja

    - name: Configure CMake (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -D"isRelease=True"

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -D"isRelease=True" -DVCPKG_TARGET_TRIPLET=x64-windows-static

    - name: Build
      run: cmake --build build --config Release

    - name: Package with CPack
      working-directory: ./build
      run: cpack -C Release

    - name: Upload to Github Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/*.zip
          build/*.tar.gz

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: battleships-${{ runner.os }}
        path: |
          build/*.zip
          build/*.tar.gz
