name: Build and Release for Windows

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -D"isRelease=True" -DVCPKG_TARGET_TRIPLET=x64-windows-static

    - name: Build
      run: cmake --build build --config Release

    - name: Package with CPack
      working-directory: ./build
      run: cpack -C Release

    - name: Upload to Github Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/*.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: battleships-windows
        path: |
          build/*.zip
          build/*.tar.gz
